<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Stealth Game</title>

    <!-- Bootstrap core CSS -->
    <link href="" rel="stylesheet">
    {{ stylesheet_link("bower_components/bootstrap/dist/css/bootstrap.min.css") }}

    <!-- Custom styles for this template -->
    {{ stylesheet_link("css/main.css") }}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      {{ stylesheet_link("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", false) }}
      {{ stylesheet_link("https://oss.maxcdn.com/respond/1.4.2/respond.min.js", false) }}
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Stealth Game</h1>
            {{ content() }}
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    {{ javascript_include("bower_components/bootstrap/dist/js/bootstrap.min.js") }}
    {{ javascript_include("bower_components/jquery/dist/jquery.min.js") }}
  </body>
</html>
